### ISSUE TITLE
Syntax for quantum function tensor product

### ISSUE THREAD

**Issue by ss2165** [CQCL/guppylang#141]
Maybe `*` to indicate the product:

```python
q0, q1 = (h*x)(q0, q1)
# equivalent to:
q0 = h(q0)
q1 = x(q1)
```

Alternatives: 
- `,` comma like BRAT, but confusion with tuples
- `|`
- `@` usually matrix multiplication so confusion with composition rather than product

**Comment by qartik** [comment]
> ```python
> q1 = h(q1)
> ```

you mean `x(q1)`, right?

Are unicode symbols such as ⊗ completely out of scope?

**Comment by ss2165** [comment]
> you mean x(q1), right?

yes, edited

**Comment by croyzor** [comment]
> @ usually matrix multiplication

It is?

**Comment by vanyae-cqc** [comment]
Having a look at this this hack week (19th-23rd)
