### ISSUE TITLE
Should `Qubit` type be lowercase `qubit`?

### ISSUE THREAD

**Issue by ss2165** [CQCL/guppylang#142]
to match other "builtins" `int, float, bool, list, linst` etc.

**Comment by croyzor** [comment]
Pros:
* More pythonic
* Reinforces that `qubit` is a built in thing to guppy

Cons:
* Syntax highlighting is a bit worse. E.g.:
```python
f(q : Qubit) # Highlighted like a type
f(q : qubit) # Plain
```
