### ISSUE TITLE
Add syntax for global variables

### ISSUE THREAD

**Issue by doug-q** [CQCL/guppylang#169]
I would like to write a guppy program such as:
```
@guppy.global(float)
rot = 1.0

@guppy
main() -> float:
  return rot
```
which compiles to a hugr containing a global Const node representing `rot`, which would be some `CustomConst` including a symbol name and a type. This Const would be further lowered to an extern symbol during codegen. 

The syntax used above is purely for explanation and I have no attachment to it.

**Comment by ss2165** [comment]
does this do the job? (it works now I believe)
```python 


rot = 1.0

@guppy
main() -> float:
  return py(rot)

```

**Comment by doug-q** [comment]
> does this do the job? (it works now I believe)

No it doesn't, although I accept this is a problem with my example. Perhaps It would be clearer to write `rot = guppy.GlobalSymbol("rot")`. The point is that I need this to compile to an external symbol.  Your example will paste "1.0" wherever `py(rot)` is written.

**Comment by ss2165** [comment]
yes 👍 
for compilation target, does this do the job: https://github.com/CQCL/hugr/issues/233

**Comment by qartik** [comment]
I think it might be easier to share intent if we replace "global" with "extern"/
"external", e.g., `ExternSymbol`.
