### ISSUE TITLE
Replace `RawHugr` with `quantinuum_hugr`'s version.

### ISSUE THREAD

**Issue by aborgna-q** [CQCL/guppylang#173]
The schema on [hugr's side](https://github.com/CQCL/hugr/blob/main/specification/schema/hugr_schema_v1.json) has been manually updated, and is currently out of sync with the pydantic definition here.

Hugr now has a python package that defines the serialization model, https://github.com/CQCL/hugr/pull/888.
We should replace the local `RawHugr` with it.

**Comment by mark-koch** [comment]
Closed by #201
