### ISSUE TITLE
ci: We are using the deprecated action for `release-please`

### ISSUE THREAD

**Issue by doug-q** [CQCL/guppylang#230]
see for example the warning here: https://github.com/CQCL/guppylang/actions/runs/9299098100

**Comment by migueltorrescosta** [comment]
I believe this has already been fixed: the [current code](https://github.com/CQCL/guppylang/blob/c7ef1849da1ab69a76a5ada90f68aeff1e001fc9/.github/workflows/release-please.yml#L19) mentions the new CI/CD action, as part of https://github.com/CQCL/guppylang/commit/c7ef1849da1ab69a76a5ada90f68aeff1e001fc9
