### ISSUE TITLE
redefining a function should be allowed

### ISSUE THREAD

**Issue by doug-q** [CQCL/guppylang#307]
when I use guppy in a notebook and I re-evaluate a cell containing a `@guppy` function definition I get an error:

```
guppylang.error.GuppyError: ('Module `main` already contains a definition named `rus`', None)
```

I suggest that instead, the existing function definition should be replaced

**Comment by mark-koch** [comment]
Should this behaviour be specific to notebooks or apply to all Guppy modules?
