### ISSUE TITLE
Add missing tket2.quantum operations to quantum module

### ISSUE THREAD

**Issue by ss2165** [CQCL/guppylang#484]
see Tk2ops, we should add missing (I can see at least Ry, CRz, Toffoli missing)

_Originally posted by @ss2165 in https://github.com/CQCL/guppylang/pull/483#discussion_r1754795839_

**Comment by jake-arkinstall** [comment]
Any chance of rushing this in on Monday? Could do with it for the notebooks (specifically crz, possibly others)

**Comment by jake-arkinstall** [comment]
I'll give it a go now
