### ISSUE TITLE
Report errors where variables are instantiated as an `@inout` type

### ISSUE THREAD

**Issue by croyzor** [CQCL/guppylang#487]
After #486, linear types get the `Inout` flag by default, but this is hidden to the user. This means the function:
```
def h(q: qubit) -> None: ...
```
has signature `qubit @inout -> None`, but will print `qubit -> None`. The problem arises when we try to unify this type. We can end up with an error message saying that unification failed comparing
```
qubit -> None
```
against
```
?T -> None
```
(see `tests/error/poly_errors/non_linear3.py`)
which is very opaque. We need a custom error message saying when unification fails by trying to instantiate a type variable to a borrowed type

**Comment by mark-koch** [comment]
Fixed in #531
