### ISSUE TITLE
Report multiple spans within the same error message

### ISSUE THREAD

**Issue by croyzor** [CQCL/guppylang#523]
Our current error reporting infrrastructure is limited to only highlighting one code span when reporting an error.
Update this to allow showing multiple code spans in error messages

This would unblock #318 and #306

**Comment by mark-koch** [comment]
> Update this to report all the error messages we can find

I think we should only focus on the multiple spans part for now. Reporting multiple errors requires us to recover from previous to keep type checking going which will require a separate refactor

**Comment by mark-koch** [comment]
See tracking issue #535

**Comment by mark-koch** [comment]
Closed by #547
