### ISSUE TITLE
Compiled module's `main` function misnamed in ipython shell.

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/guppylang#661]
When compiling guppy in an ipython shell, instead of the main function being called `main`, it is called something like `<ipython-input-3-3e9b5833de21>` in the compiled hugr.

For example:
```
alec@QuantUK-6R64C14:~/r/guppy-integration$ uv run ipython
Python 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.29.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from guppylang import guppy
   ...: from guppylang.std.builtins import result
   ...: from guppylang.std.quantum import h, measure, qubit

In [2]: @guppy
   ...: def main() -> None:
   ...:     q0 = qubit()
   ...:     h(q0)
   ...:     result("m", measure(q0))
   ...: 

In [3]: out = guppy.compile_module()

In [4]: "main" in str(out)
Out[4]: False
```

**Comment by mark-koch** [comment]
The `<ipython-input-3-3e9b5833de21>` is actually the name of the module. The main function isn't even being compiled...

**Comment by cqc-alec** [comment]
> The `<ipython-input-3-3e9b5833de21>` is actually the name of the module. The main function isn't even being compiled...

Ah yes you're right.
